import { useState } from 'react';
import './App.css';
import Faq from "react-faq-component";
import stepOne from './images/stepone.png';
import stepOneBuildings from './images/stepone-buildings.png';
import stepTwo from './images/steptwo.png';
import stepThree from './images/stepthree.png';
import downArrow from './images/down-arrow.png';

const data = {
  rows: [
    {
      title: "What exactly does the antenna do?",
      content: <p>The antenna and its associated hardware will broadcast your internet connection through a 5G wireless signal that phones can connect to.
        It's essentially a wireless router, but with a 5G signal. Customers of <a rel="noopener noreferrer" href='https://www.pollenmobile.io/how-it-works'>Pollen Mobile</a> and <a rel="noopener noreferrer" href='https://hellohelium.com/'>Helium Mobile</a> will 
        be able to connect to the internet through your setup.</p>,
    },
    {
      title: "How is the antenna installed?",
      content:
        <>
          <p>The antenna(s) can be installed on any existing poles or sturdy structures on the roof of your building.
            We can also install a new pole if needed. Here are examples of other installations:</p>
          <div className='examples'>
            <img className='example-image' src='https://cdn.discordapp.com/attachments/951232662436204605/979156620372226129/WhatsApp_Image_2022-05-25_at_8.00.21_PM.jpeg'></img>
            <img className='example-image' src='https://cdn.discordapp.com/attachments/951232662436204605/994362702485008395/IMG_2830.jpg'></img>
            <img className='example-image' src='https://cdn.discordapp.com/attachments/951232662436204605/1006022517607116882/123_1.jpg'></img>
          </div>
        </>
    },
    {
      title: "How much does it cost to install? Does it cost me anything to run or use?",
      content: `Our service is free and will take care of installation and maintenance. Customers pay Pollen and Helium to use the internet, and you get paid for letting them use it! The only thing you provide is power and internet access.`
    },
    {
      title: "How much money can I make?",
      content: `Payment rate will be determined by factors such as location, height, and number of antennas. We will provide you with a quote based on your location and building.`,
    },
    {
      title: "How do I get paid?",
      content: `Payment will usually be an agreed upon flat amount per month, but can also be a percentage of the revenue generated by the antennas. We will work with you to determine the best payment method for you.`,
    },
    {
      title: "What if my roof/installation site doesn't have power/internet?",
      content: `We can work with you to find a solution. We can install a solar panel and battery to power the antenna, and we can install a new internet connection  .`
    },
  ]
};

const styles = {
  bgColor: 'rgba(0,0,0,0.3)',
  titleTextColor: "#afece7",
  rowTitleColor: "#afece7",
  rowContentColor: 'white',
  arrowColor: "white",
};

const config = {
  // animate: true,
  // arrowIcon: "V",
  // tabFocus: true
};

function App() {
  let [open, setOpen] = useState(false);
  let customClass = "";
  if (open) {
    customClass = "open";
  }
  return (
    <div className="App">
      <div className="section" id="section1">
        <div className='step-list'>
          <div className='step' id='step-one'>
            <div className='step-image'>
              <div className='step-top-gradient'></div>
              <img src={stepOneBuildings} className='step-bottom'></img>
            </div>
            <div className='step-content'>
              🛠 We set up
            </div>
            <div className='step-content-lower'>
              5g antenna(s) on your roof, for free!
            </div>
          </div>
          <div className='step' id='step-two'>
            <div className='step-image'>
              <img src={stepTwo} className='step-top'></img>
            </div>
            <div className='step-content'>
              📶 Customers connect
            </div>
            <div className='step-content-lower'>
              to the internet through your antenna(s). They will pay Pollen and Helium for the service.
            </div>
          </div>
          <div className='step' id='step-three'>
            <div className='step-image'>
              <img src={stepThree} className='step-top'></img>
            </div>
            <div className='step-content'>
              💰 Get rewards!!
            </div>
            <div className='step-content-lower'>
              Those funds come back to you for letting customers use your antenna(s)!
            </div>
          </div>

        </div>
        <div onClick={() => document.getElementById("howsItWork").scrollIntoView({ behavior: 'smooth' })} className='howsItWork' id='howsItWork'>
          <img className='down-arrow' src={downArrow}></img>
          How's it work?
        </div>
      </div>
      <div className="section" id='section2'>
        <Faq
          data={data}
          styles={styles}
          config={config}
        />
      </div>
    </div>
  );
}

export default App;


